/*
 * This file is generated by @figma-normalizator/codegen-tokens.
 * DO NOT MODIFY -- any manual changes will be overwritten the next time
 * tokens are regenerated from Figma.
 */

package com.example.tokens

@androidx.compose.runtime.Immutable
data class Base(
    val color: Color,
    val layout: Layout,
) {
    /**
     * @property surface Semantic surface color, aliases primitives/color/red in every mode. (symbol: `AppTheme.color.surface`, via wiring rule `base-color`)
     */
    @androidx.compose.runtime.Immutable
    data class Color(
        val surface: androidx.compose.ui.graphics.Color,
    )
    /**
     * @property `is` Deliberately named 'is' to exercise Kotlin keyword escaping.
     */
    @androidx.compose.runtime.Immutable
    data class Layout(
        val `is`: Boolean,
    )
}

fun baseLight(primitives: Primitives): Base =
    Base(
        color = Base.Color(
            surface = primitives.color.red,
        ),
        layout = Base.Layout(
            `is` = true,
        ),
    )

fun baseDark(primitives: Primitives): Base =
    Base(
        color = Base.Color(
            surface = primitives.color.red,
        ),
        layout = Base.Layout(
            `is` = false,
        ),
    )
