/*
 * This file is generated by @figma-normalizator/codegen-tokens.
 * DO NOT MODIFY -- any manual changes will be overwritten the next time
 * tokens are regenerated from Figma.
 */

package com.example.tokens

@androidx.compose.runtime.Immutable
data class Primitives(
    val color: Color,
    val spacing: Spacing,
) {
    /**
     * @property red Primitive red, used directly by base's surface color.
     */
    @androidx.compose.runtime.Immutable
    data class Color(
        val red: androidx.compose.ui.graphics.Color,
    )
    @androidx.compose.runtime.Immutable
    data class Spacing(
        val small: Float,
    )
}

fun primitivesValue(): Primitives =
    Primitives(
        color = Primitives.Color(
            red = androidx.compose.ui.graphics.Color(1.0f, 0.0f, 0.0f, 1.0f),
        ),
        spacing = Primitives.Spacing(
            small = 8.0f,
        ),
    )
