// CLI orchestration (migration plan, stage 7.1/7.3): wires the input,
// model, and emit layers into the actual `codegen-tokens` command --
// load, validate policy freshness, triage `unresolved[]`, build the model,
// generate Kotlin, then either write it, report it (--dry-run), or diff it
// against the existing output (--check, the same doctrine as
// `scripts/verify-generated.mjs`).
import { mkdir, readdir, readFile, rm, rmdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { loadTokenDocument } from "../input/load.js";
import { assertPolicyFresh, warnAboutUnmatchedPolicyPatterns } from "../input/policy.js";
import { assertNoUnresolvedFailures } from "../input/unresolved.js";
import { buildTokenModel } from "../model/build.js";
import { generateKotlinFiles, generateLegacyKotlinFiles, type KotlinFile } from "../emit/kotlin.js";
import { CliArgError, HELP_TEXT, parseArgs, type CliOptions } from "./args.js";

/**
 * The first line of `kotlinGeneratedHeader()`. A file under `--output`
 * is only ever deleted as stale if it carries this -- see
 * `findStaleGeneratedFiles`.
 */
const GENERATED_MARKER = "This file is generated by @figma-normalizator/codegen-tokens.";

/** Recursively yields every `.kt` file under `dir`, sorted for deterministic output. */
async function listKotlinFiles(dir: string): Promise<string[]> {
  const entries = await readdir(dir, { withFileTypes: true }).catch(() => []);
  const found: string[] = [];
  for (const entry of [...entries].sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) found.push(...(await listKotlinFiles(full)));
    else if (entry.isFile() && entry.name.endsWith(".kt")) found.push(full);
  }
  return found;
}

/**
 * Generated files that exist under `outputDir` but are NOT in this run's
 * output -- a collection or branch that was renamed or deleted in Figma, a
 * mode that `--exclude-mode` now filters out, or the whole previous
 * `--layout`. Writing is not enough to make the output directory correct:
 * without this, those files just sit there and keep compiling into the
 * consuming app, which is how a token deleted in Figma stays alive in
 * Android for months.
 *
 * Deliberately narrow: `--output` can legitimately be a directory that
 * also holds hand-written Kotlin, so this only ever considers a file stale
 * if it carries the emitter's own "DO NOT MODIFY" banner. Anything this
 * generator did not write is left strictly alone, which is why it reports
 * files instead of wiping the directory.
 */
async function findStaleGeneratedFiles(
  outputDir: string,
  files: readonly KotlinFile[],
): Promise<string[]> {
  const keep = new Set(files.map((f) => path.resolve(outputDir, f.relativePath)));
  const stale: string[] = [];
  for (const candidate of await listKotlinFiles(outputDir)) {
    if (keep.has(path.resolve(candidate))) continue;
    const contents = await readFile(candidate, "utf8").catch(() => "");
    if (contents.includes(GENERATED_MARKER)) stale.push(candidate);
  }
  return stale;
}

/**
 * Removes directories left empty by pruning, walking up from each deleted
 * file but never past `outputDir` itself (an empty `--output` is a valid
 * result of generating nothing, and is not this function's to remove). A
 * directory that still holds anything -- including a hand-written file
 * pruning deliberately kept -- makes `rmdir` fail, which is exactly the
 * intended stop condition, so the error is swallowed.
 */
async function pruneEmptyDirs(outputDir: string, deleted: readonly string[]): Promise<void> {
  const root = path.resolve(outputDir);
  const dirs = [...new Set(deleted.map((f) => path.resolve(path.dirname(f))))];
  // Deepest first, so a parent is only tried after its children are gone.
  dirs.sort((a, b) => b.length - a.length);
  for (const dir of dirs) {
    let current = dir;
    while (current !== root && current.startsWith(root + path.sep)) {
      const ok = await rmdir(current).then(
        () => true,
        () => false,
      );
      if (!ok) break;
      current = path.dirname(current);
    }
  }
}

export interface CliIo {
  stdout: (message: string) => void;
  stderr: (message: string) => void;
}

const defaultIo: CliIo = {
  stdout: (m) => console.log(m),
  stderr: (m) => console.error(m),
};

/** Runs the CLI end-to-end for already-tokenized `argv`. Returns the process exit code. */
export async function runCli(argv: readonly string[], io: CliIo = defaultIo): Promise<number> {
  let options: CliOptions;
  try {
    options = parseArgs(argv);
  } catch (error) {
    if (error instanceof CliArgError) {
      io.stderr(error.message);
      return error.message === HELP_TEXT ? 0 : 1;
    }
    throw error;
  }

  try {
    const document = await loadTokenDocument(options.input);
    assertPolicyFresh(document.policy, options.input);
    warnAboutUnmatchedPolicyPatterns(document.policy, io.stderr);
    assertNoUnresolvedFailures(document.unresolved, options.onUnresolved, io.stderr);

    const model = buildTokenModel(document);
    const emitOptions = {
      packageName: options.packageName,
      excludeModePattern: options.excludeMode,
      classPrefix: options.prefix,
    };
    const files =
      options.layout === "legacy"
        ? generateLegacyKotlinFiles(model, emitOptions)
        : generateKotlinFiles(model, emitOptions);

    if (options.check) {
      return await checkAgainstDisk(files, options.output, io);
    }
    const stale = await findStaleGeneratedFiles(options.output, files);
    if (options.dryRun) {
      for (const file of files)
        io.stdout(`would write ${path.join(options.output, file.relativePath)}`);
      for (const file of stale) io.stdout(`would delete (no longer generated) ${file}`);
      io.stdout(
        `${files.length} file(s) would be generated, ${stale.length} stale file(s) would be ` +
          `deleted (--dry-run, nothing written).`,
      );
      return 0;
    }

    for (const file of files) {
      const dest = path.join(options.output, file.relativePath);
      await mkdir(path.dirname(dest), { recursive: true });
      await writeFile(dest, file.contents, "utf8");
      io.stdout(`wrote ${dest}`);
    }
    for (const file of stale) {
      await rm(file, { force: true });
      io.stdout(`deleted (no longer generated) ${file}`);
    }
    await pruneEmptyDirs(options.output, stale);
    io.stdout(`${files.length} file(s) generated, ${stale.length} stale file(s) deleted.`);
    return 0;
  } catch (error) {
    io.stderr(error instanceof Error ? error.message : String(error));
    return 1;
  }
}

/**
 * Generates into memory and diffs against what's already on disk at
 * `outputDir`, without writing anything -- the same gate doctrine as
 * `scripts/verify-generated.mjs`: a mismatch means the output is stale
 * relative to its input and must be regenerated before landing. A
 * previously-generated file that this run no longer produces counts as a
 * mismatch too: leaving it on disk is precisely the staleness this gate
 * exists to catch.
 */
async function checkAgainstDisk(
  files: readonly KotlinFile[],
  outputDir: string,
  io: CliIo,
): Promise<number> {
  let stale = false;
  for (const file of files) {
    const dest = path.join(outputDir, file.relativePath);
    let onDisk: string | undefined;
    try {
      onDisk = await readFile(dest, "utf8");
    } catch {
      onDisk = undefined;
    }
    if (onDisk !== file.contents) {
      stale = true;
      io.stderr(`stale or missing: ${dest}`);
    }
  }
  const orphans = await findStaleGeneratedFiles(outputDir, files);
  for (const orphan of orphans) {
    stale = true;
    io.stderr(`stale (no longer generated): ${orphan}`);
  }
  if (stale) {
    io.stderr("output is stale -- run without --check to regenerate.");
    return 1;
  }
  io.stdout(`${files.length} file(s) are up to date.`);
  return 0;
}
