"""Shared codegen utilities — naming, formatting, file writing."""
from __future__ import annotations

import os
import re
from abc import ABC, abstractmethod
from typing import Any, List, Optional, Tuple

from ..figma.models import FigmaColorValue, ResolvedToken, TokenType
from ..config import GeneratorConfig


KOTLIN_KEYWORDS = frozenset([
    "as", "break", "class", "continue", "do", "else", "false", "for", "fun",
    "if", "in", "interface", "is", "null", "object", "package", "return",
    "super", "this", "throw", "true", "try", "typealias", "typeof", "val",
    "var", "when", "while",
])


class TokenGenerator(ABC):
    """Interface for language-specific code generators."""

    @property
    @abstractmethod
    def language_id(self) -> str: ...

    @abstractmethod
    def generate(self, tokens: List[ResolvedToken], config: GeneratorConfig) -> None: ...


# --- Naming utilities ---

def sanitize_path(path: str) -> List[str]:
    segments = path.split("/")
    return [re.sub(r"[^\x00-\x7f]", "", s).strip() for s in segments if re.sub(r"[^\x00-\x7f]", "", s).strip()]


def sanitize_identifier(name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9_ ]", "", name).strip()
    return "".join(part.capitalize() for part in re.split(r"[\s_]+", clean) if part)


def to_folder_name(name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9 _-]", "", name).strip()
    return "".join(part.lower() for part in re.split(r"[\s_-]+", clean) if part)


def _join_parts_disambiguated(parts: List[str], titled: List[str]) -> str:
    """Join capitalized/titled word parts, inserting '_' between two purely
    numeric parts so e.g. ["12", "5"] (from "12-5") doesn't collapse into the
    same identifier as a single numeric part ["125"] (from "125")."""
    result = ""
    prev_numeric = False
    for raw, part in zip(parts, titled):
        numeric = raw.isdigit()
        if result and prev_numeric and numeric:
            result += "_"
        result += part
        prev_numeric = numeric
    return result


def to_camel_case(name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9 _-]", "", name).strip()
    if not clean:
        return "_empty"
    parts = [p for p in re.split(r"[\s_-]+", clean) if p]
    titled = [
        part[0].lower() + part[1:] if i == 0 else part[0].upper() + part[1:]
        for i, part in enumerate(parts)
    ]
    result = _join_parts_disambiguated(parts, titled)
    return f"_{result}" if result[0].isdigit() else result


def to_pascal_case(name: str) -> str:
    clean = re.sub(r"[^A-Za-z0-9 _-]", "", name).strip()
    if not clean:
        return "Empty"
    parts = [p for p in re.split(r"[\s_-]+", clean) if p]
    titled = [part[0].upper() + part[1:] for part in parts]
    result = _join_parts_disambiguated(parts, titled)
    return f"N{result}" if result[0].isdigit() else result


# --- Value formatting ---

def _round_float(v: float) -> str:
    if v == 0.0:
        return "0.0"
    if v == 1.0:
        return "1.0"
    rounded = float(f"{v:.8g}")
    s = f"{rounded:g}"
    if "." not in s and "e" not in s:
        s += ".0"
    return s


def format_color_kotlin(value: Any) -> str:
    color_name = "androidx.compose.ui.graphics.Color"
    if isinstance(value, FigmaColorValue):
        r, g, b, a = _round_float(value.r), _round_float(value.g), _round_float(value.b), _round_float(value.a)
        return f"{color_name}({r}f, {g}f, {b}f, {a}f)"
    if isinstance(value, dict) and "r" in value:
        r, g, b, a = _round_float(float(value['r'])), _round_float(float(value['g'])), _round_float(float(value['b'])), _round_float(float(value.get('a', 1.0)))
        return f"{color_name}({r}f, {g}f, {b}f, {a}f)"
    return f"{color_name}.Unspecified"


def format_float_kotlin(value: Any) -> str:
    num = float(value) if not isinstance(value, float) else value
    return f"{_round_float(num)}f"


def format_color_swift(value: Any) -> str:
    if isinstance(value, FigmaColorValue):
        r, g, b, a = _round_float(value.r), _round_float(value.g), _round_float(value.b), _round_float(value.a)
        return f"Color(red: {r}, green: {g}, blue: {b}, opacity: {a})"
    if isinstance(value, dict) and "r" in value:
        r, g, b, a = _round_float(float(value['r'])), _round_float(float(value['g'])), _round_float(float(value['b'])), _round_float(float(value.get('a', 1.0)))
        return f"Color(red: {r}, green: {g}, blue: {b}, opacity: {a})"
    return "Color.clear"


def format_float_swift(value: Any) -> str:
    num = float(value) if not isinstance(value, float) else value
    return _round_float(num)


def escape_string(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


# --- Generated-file banner & documentation comments ---

GENERATED_NOTICE_LINES = [
    "This file is generated by the figma-tokens tool.",
    "DO NOT MODIFY — any manual changes will be overwritten the next time",
    "tokens are regenerated from Figma.",
]

_BLOCK_COMMENT_EXTS = {".kt", ".kts", ".java"}
_LINE_COMMENT_EXTS = {".swift"}


def generated_header(path: str) -> str:
    """Return the 'do not edit' banner for the given file, or '' if unsupported."""
    ext = os.path.splitext(path)[1]
    if ext in _BLOCK_COMMENT_EXTS:
        body = "\n".join(f" * {line}" for line in GENERATED_NOTICE_LINES)
        return f"/*\n{body}\n */\n"
    if ext in _LINE_COMMENT_EXTS:
        return "\n".join(f"// {line}" for line in GENERATED_NOTICE_LINES) + "\n"
    return ""


def normalize_doc(description: Optional[str]) -> str:
    """Collapse a Figma description into a single-line, comment-safe string."""
    if not description:
        return ""
    text = " ".join(description.split())
    return text.replace("*/", "*\\/")


def doc_lines(description: Optional[str]) -> List[str]:
    """Split a Figma description into comment-safe lines (blank lines dropped)."""
    if not description:
        return []
    return [
        " ".join(line.split()).replace("*/", "*\\/")
        for line in description.replace("\r\n", "\n").split("\n")
        if line.strip()
    ]


def kdoc_block(entries: List[Tuple[str, str]], pad: str = "") -> List[str]:
    """Build a KDoc block documenting constructor properties.

    `entries` are (propertyName, description) pairs; entries without a
    description are skipped, and an empty block yields no lines.
    """
    documented = [(name, normalize_doc(desc)) for name, desc in entries]
    documented = [(name, desc) for name, desc in documented if desc]
    if not documented:
        return []
    lines = [f"{pad}/**"]
    for name, desc in documented:
        lines.append(f"{pad} * @property {name} {desc}")
    lines.append(f"{pad} */")
    return lines


def swift_doc(description: Optional[str], pad: str = "") -> List[str]:
    """Build DocC `///` comment lines for a property."""
    return [f"{pad}/// {line}" for line in doc_lines(description)]


def kotlin_type(token_type: TokenType) -> str:
    return {
        TokenType.COLOR: "androidx.compose.ui.graphics.Color",
        TokenType.FLOAT: "Float",
        TokenType.STRING: "String",
        TokenType.BOOLEAN: "Boolean",
    }[token_type]


def swift_type(token_type: TokenType) -> str:
    return {
        TokenType.COLOR: "Color",
        TokenType.FLOAT: "CGFloat",
        TokenType.STRING: "String",
        TokenType.BOOLEAN: "Bool",
    }[token_type]


def write_file(path: str, content: str) -> None:
    """Write a generated file, prefixed with the 'do not edit' banner."""
    os.makedirs(os.path.dirname(path), exist_ok=True)
    header = generated_header(path)
    if header:
        content = f"{header}\n{content.lstrip()}" if content.strip() else header
    with open(path, "w") as f:
        f.write(content)


# Re-export tree utilities so generators can import from .base
from ..pipeline.tree import TreeNode, insert_token, collect_all_tokens  # noqa: E402
